import {
  DataSource,
  CatalogDatabase,
  CatalogTable,
  ActivityLog,
  OverviewKPIs,
  UserProfile,
} from '../types';

export const CURRENT_USER: UserProfile = {
  id: 'usr_enterprise_001',
  name: 'Marcus Vance',
  email: 'm.vance@acmecorp.internal',
  role: 'Data Architect',
  department: 'Enterprise Data Platform',
  organization: 'Acme Global Operations',
  lastLogin: '2026-08-17 22:45 UTC',
};

export const INITIAL_KPIS: OverviewKPIs = {
  connectedSources: 12,
  healthyConnections: 10,
  catalogedTables: 248,
  availableSchemas: 36,
  totalRecordsEstimate: '4.82 Billion',
  storageUsageGb: 3840,
  syncFreshnessPercentage: 98.4,
  cacheHitRatio: 94.2,
};

export const MOCK_DATA_SOURCES: DataSource[] = [
  {
    id: 'src_sf_prod_sales',
    name: 'Sales & Revenue Warehouse',
    platform: 'snowflake',
    environment: 'production',
    status: 'healthy',
    accountIdentifier: 'xy94821.us-east-1',
    warehouse: 'COMPUTE_WH_XL',
    database: 'RETAIL_ANALYTICS',
    defaultSchema: 'SALES',
    username: 'SVC_PI_ANALYTICS_RO',
    role: 'DATA_DISCOVERY_ROLE',
    lastSyncAt: '3 mins ago',
    tableCount: 48,
    schemaCount: 6,
    recordCountEstimate: '1.24B',
    storageSizeGb: 1420,
    region: 'AWS us-east-1 (N. Virginia)',
    createdAt: '2026-01-14',
    autoSyncEnabled: true,
    syncIntervalMinutes: 15,
  },
  {
    id: 'src_sf_cust_hub',
    name: 'Customer 360 Warehouse',
    platform: 'snowflake',
    environment: 'production',
    status: 'healthy',
    accountIdentifier: 'xy94821.us-east-1',
    warehouse: 'ANALYTICS_WH_M',
    database: 'CUSTOMER_DATA_HUB',
    defaultSchema: 'CORE',
    username: 'SVC_PI_ANALYTICS_RO',
    role: 'DATA_DISCOVERY_ROLE',
    lastSyncAt: '8 mins ago',
    tableCount: 72,
    schemaCount: 8,
    recordCountEstimate: '890M',
    storageSizeGb: 980,
    region: 'AWS us-east-1 (N. Virginia)',
    createdAt: '2026-02-01',
    autoSyncEnabled: true,
    syncIntervalMinutes: 30,
  },
  {
    id: 'src_sf_mktg_attr',
    name: 'Marketing Attribution Mart',
    platform: 'snowflake',
    environment: 'production',
    status: 'warning',
    accountIdentifier: 'xy94821.us-east-1',
    warehouse: 'MARKETING_WH_S',
    database: 'MARKETING_ATTRIBUTION',
    defaultSchema: 'CAMPAIGNS',
    username: 'SVC_PI_ANALYTICS_RO',
    role: 'DATA_DISCOVERY_ROLE',
    lastSyncAt: '1 hour ago',
    tableCount: 31,
    schemaCount: 4,
    recordCountEstimate: '340M',
    storageSizeGb: 420,
    region: 'AWS us-east-1 (N. Virginia)',
    createdAt: '2026-02-28',
    autoSyncEnabled: true,
    syncIntervalMinutes: 60,
    errorMessage: 'Warehouse auto-resume timed out during schema introspection',
  },
  {
    id: 'src_sf_fin_ledger',
    name: 'Finance & General Ledger',
    platform: 'snowflake',
    environment: 'production',
    status: 'healthy',
    accountIdentifier: 'xy94821.us-east-1',
    warehouse: 'FINANCE_SECURE_WH',
    database: 'FINANCE_LEDGER_PROD',
    defaultSchema: 'GL',
    username: 'SVC_PI_FIN_RO',
    role: 'FINANCE_AUDITOR_ROLE',
    lastSyncAt: '22 mins ago',
    tableCount: 54,
    schemaCount: 7,
    recordCountEstimate: '610M',
    storageSizeGb: 760,
    region: 'AWS us-east-1 (N. Virginia)',
    createdAt: '2026-03-10',
    autoSyncEnabled: true,
    syncIntervalMinutes: 30,
  },
  {
    id: 'src_sf_staging_etl',
    name: 'Staging Ingestion Inbound',
    platform: 'snowflake',
    environment: 'staging',
    status: 'healthy',
    accountIdentifier: 'xy94821.us-east-1',
    warehouse: 'INGESTION_WH_L',
    database: 'RAW_INGESTION_STAGING',
    defaultSchema: 'LANDING',
    username: 'SVC_PI_STAGING',
    role: 'STAGING_RO',
    lastSyncAt: '45 mins ago',
    tableCount: 43,
    schemaCount: 5,
    recordCountEstimate: '1.74B',
    storageSizeGb: 1260,
    region: 'AWS us-east-1 (N. Virginia)',
    createdAt: '2026-04-05',
    autoSyncEnabled: false,
    syncIntervalMinutes: 120,
  },
  {
    id: 'src_db_lakehouse_preview',
    name: 'Delta Lake Unified Telemetry',
    platform: 'databricks',
    environment: 'development',
    status: 'disconnected',
    accountIdentifier: 'dbc-98421a-west.cloud.databricks.com',
    warehouse: 'SQL_SERVERLESS_01',
    database: 'UNITY_CATALOG_DEV',
    defaultSchema: 'TELEMETRY',
    username: 'svc_databricks_ro',
    role: 'CATALOG_READER',
    lastSyncAt: 'Never',
    tableCount: 0,
    schemaCount: 0,
    recordCountEstimate: '0',
    storageSizeGb: 0,
    region: 'Azure East US 2',
    createdAt: '2026-08-01',
    autoSyncEnabled: false,
    syncIntervalMinutes: 60,
  },
];

export const MOCK_TABLE_ORDER_FACT: CatalogTable = {
  id: 'tbl_order_fact',
  name: 'ORDER_FACT',
  database: 'RETAIL_ANALYTICS',
  schema: 'SALES',
  sourceId: 'src_sf_prod_sales',
  sourceName: 'Sales & Revenue Warehouse',
  description: 'Core transactional fact table recording completed customer orders, line amounts, discount allocations, and fulfillment statuses partitioned by order date.',
  owner: 'DATA_PLATFORM_TEAM',
  rowCount: 142850900,
  sizeBytes: 148200000000,
  sizeFormatted: '138.0 GB',
  lastModifiedAt: '2026-08-17 21:30:00 UTC',
  lastSyncedAt: '3 mins ago',
  tags: ['production', 'certified', 'tier-1-financial', 'dbt-gold', 'pci-compliant'],
  downstreamDashboards: ['Executive Revenue Cockpit', 'Regional Sales QBR', 'Customer Retention Monitor'],
  ddl: `CREATE OR REPLACE TABLE RETAIL_ANALYTICS.SALES.ORDER_FACT (
    ORDER_ID NUMBER(38,0) NOT NULL,
    ORDER_NUMBER VARCHAR(64) NOT NULL,
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    ORDER_TIMESTAMP TIMESTAMP_NTZ(9) NOT NULL,
    ORDER_STATUS VARCHAR(32) NOT NULL,
    NET_AMOUNT NUMBER(18,2) NOT NULL,
    TAX_AMOUNT NUMBER(18,2) NOT NULL,
    SHIPPING_AMOUNT NUMBER(18,2) DEFAULT 0.00,
    TOTAL_AMOUNT NUMBER(18,2) NOT NULL,
    PAYMENT_METHOD VARCHAR(32),
    CURRENCY_CODE VARCHAR(3) DEFAULT 'USD',
    IS_EXPEDITED_SHIPPING BOOLEAN DEFAULT FALSE,
    FULFILLMENT_CENTER_ID VARCHAR(32),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_ORDER_FACT PRIMARY KEY (ORDER_ID)
)
CLUSTER BY (ORDER_TIMESTAMP, CUSTOMER_ID);`,
  columns: [
    {
      name: 'ORDER_ID',
      type: 'NUMBER(38,0)',
      nullable: false,
      isPrimaryKey: true,
      description: 'Surrogate primary key for the transactional order record',
      sampleValues: [90841201, 90841202, 90841203, 90841204, 90841205],
      distinctCount: 142850900,
      nullPercentage: 0,
    },
    {
      name: 'ORDER_NUMBER',
      type: 'VARCHAR(64)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Human-readable order tracking string presented to buyers (e.g. ORD-2026-88912)',
      sampleValues: ['ORD-2026-88912', 'ORD-2026-88913', 'ORD-2026-88914', 'ORD-2026-88915'],
      distinctCount: 142850900,
      nullPercentage: 0,
    },
    {
      name: 'CUSTOMER_ID',
      type: 'NUMBER(38,0)',
      nullable: false,
      isPrimaryKey: false,
      isForeignKey: true,
      foreignKeyTarget: 'RETAIL_ANALYTICS.CUSTOMERS.CUSTOMER_DIM.CUSTOMER_ID',
      description: 'Foreign key reference to dimension customer record',
      sampleValues: [1004921, 1083920, 2093181, 1004921, 3948201],
      distinctCount: 4210900,
      nullPercentage: 0,
    },
    {
      name: 'ORDER_TIMESTAMP',
      type: 'TIMESTAMP_NTZ(9)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Exact UTC timestamp of when order was finalized by checkout gateway',
      sampleValues: ['2026-08-17 21:14:02', '2026-08-17 21:15:33', '2026-08-17 21:16:01'],
      distinctCount: 98400200,
      nullPercentage: 0,
    },
    {
      name: 'ORDER_STATUS',
      type: 'VARCHAR(32)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Lifecycle state: COMPLETED, PROCESSING, REFUNDED, CANCELLED, ON_HOLD',
      sampleValues: ['COMPLETED', 'PROCESSING', 'COMPLETED', 'REFUNDED'],
      distinctCount: 5,
      nullPercentage: 0,
    },
    {
      name: 'NET_AMOUNT',
      type: 'NUMBER(18,2)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Total item prices prior to applied sales tax and freight',
      sampleValues: [149.99, 42.50, 1289.00, 320.40, 89.00],
      distinctCount: 14920,
      nullPercentage: 0,
    },
    {
      name: 'TAX_AMOUNT',
      type: 'NUMBER(18,2)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Calculated regional and municipal sales tax',
      sampleValues: [12.37, 3.51, 106.34, 26.43, 7.34],
      distinctCount: 4890,
      nullPercentage: 0,
    },
    {
      name: 'SHIPPING_AMOUNT',
      type: 'NUMBER(18,2)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Fulfillment and courier delivery fee',
      sampleValues: [0.00, 9.99, 14.99, 0.00, 4.99],
      distinctCount: 24,
      nullPercentage: 0,
    },
    {
      name: 'TOTAL_AMOUNT',
      type: 'NUMBER(18,2)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Final settled charge billed to customer payment instrument',
      sampleValues: [162.36, 56.00, 1410.34, 346.83, 101.33],
      distinctCount: 21400,
      nullPercentage: 0,
    },
    {
      name: 'PAYMENT_METHOD',
      type: 'VARCHAR(32)',
      nullable: true,
      isPrimaryKey: false,
      description: 'Primary tokenized processor: STRIPE_CARD, APPLE_PAY, PAYPAL, INVOICE_NET30',
      sampleValues: ['STRIPE_CARD', 'APPLE_PAY', 'STRIPE_CARD', 'PAYPAL'],
      distinctCount: 6,
      nullPercentage: 0.2,
    },
    {
      name: 'CURRENCY_CODE',
      type: 'VARCHAR(3)',
      nullable: false,
      isPrimaryKey: false,
      description: 'ISO-4217 standard 3-character transaction currency code',
      sampleValues: ['USD', 'EUR', 'GBP', 'CAD', 'JPY'],
      distinctCount: 8,
      nullPercentage: 0,
    },
    {
      name: 'IS_EXPEDITED_SHIPPING',
      type: 'BOOLEAN',
      nullable: false,
      isPrimaryKey: false,
      description: 'Flag indicating express 24-hour priority air transport',
      sampleValues: [false, true, false, false, true],
      distinctCount: 2,
      nullPercentage: 0,
    },
    {
      name: 'FULFILLMENT_CENTER_ID',
      type: 'VARCHAR(32)',
      nullable: true,
      isPrimaryKey: false,
      description: 'Origin distribution warehouse identifier (e.g. WH-EAST-04)',
      sampleValues: ['WH-EAST-04', 'WH-CENTRAL-01', 'WH-WEST-02'],
      distinctCount: 14,
      nullPercentage: 1.4,
    },
    {
      name: 'CREATED_AT',
      type: 'TIMESTAMP_NTZ(9)',
      nullable: false,
      isPrimaryKey: false,
      description: 'System ingestion timestamp in Snowflake target table',
      sampleValues: ['2026-08-17 21:14:15', '2026-08-17 21:15:45'],
      distinctCount: 98400200,
      nullPercentage: 0,
    },
  ],
};

export const MOCK_TABLE_CUSTOMER_DIM: CatalogTable = {
  id: 'tbl_customer_dim',
  name: 'CUSTOMER_DIM',
  database: 'RETAIL_ANALYTICS',
  schema: 'CUSTOMERS',
  sourceId: 'src_sf_prod_sales',
  sourceName: 'Sales & Revenue Warehouse',
  description: 'Conformed dimensional customer profile containing verified identity attributes, lifetime value tiers, demographic segments, and GDPR consent state.',
  owner: 'CRM_ENGINEERING',
  rowCount: 4210900,
  sizeBytes: 4200000000,
  sizeFormatted: '3.91 GB',
  lastModifiedAt: '2026-08-17 19:15:00 UTC',
  lastSyncedAt: '3 mins ago',
  tags: ['production', 'pii-governed', 'scd-type-2', 'crm'],
  downstreamDashboards: ['Customer Lifetime Value', 'Churn Risk Predictor', 'Cohort Retention'],
  ddl: `CREATE OR REPLACE TABLE RETAIL_ANALYTICS.CUSTOMERS.CUSTOMER_DIM (
    CUSTOMER_ID NUMBER(38,0) NOT NULL,
    CUSTOMER_UUID VARCHAR(36) NOT NULL,
    FIRST_NAME VARCHAR(128) NOT NULL,
    LAST_NAME VARCHAR(128) NOT NULL,
    EMAIL VARCHAR(256) NOT NULL,
    PHONE_NUMBER VARCHAR(32),
    CUSTOMER_TIER VARCHAR(32) DEFAULT 'STANDARD',
    LIFETIME_VALUE_USD NUMBER(18,2) DEFAULT 0.00,
    COUNTRY_CODE VARCHAR(2) DEFAULT 'US',
    ACCOUNT_STATUS VARCHAR(32) DEFAULT 'ACTIVE',
    GDPR_CONSENT_GRANTED BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CUSTOMER_DIM PRIMARY KEY (CUSTOMER_ID)
);`,
  columns: [
    {
      name: 'CUSTOMER_ID',
      type: 'NUMBER(38,0)',
      nullable: false,
      isPrimaryKey: true,
      description: 'Unique internal customer surrogate key',
      sampleValues: [1004921, 1083920, 2093181, 3948201, 4019283],
      distinctCount: 4210900,
      nullPercentage: 0,
    },
    {
      name: 'CUSTOMER_UUID',
      type: 'VARCHAR(36)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Globally unique canonical UUID across all frontend auth portals',
      sampleValues: ['d8b2e5a1-7c9f-4e3b-9a8d-1f2e3d4c5b6a', 'a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d'],
      distinctCount: 4210900,
      nullPercentage: 0,
    },
    {
      name: 'FIRST_NAME',
      type: 'VARCHAR(128)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Customer given name',
      sampleValues: ['Eleanor', 'David', 'Sophia', 'Lucas', 'Amara'],
      distinctCount: 84000,
      nullPercentage: 0,
    },
    {
      name: 'LAST_NAME',
      type: 'VARCHAR(128)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Customer family / surname',
      sampleValues: ['Sterling', 'Chen', 'Montgomery', 'Kowalski', 'Okafor'],
      distinctCount: 142000,
      nullPercentage: 0,
    },
    {
      name: 'EMAIL',
      type: 'VARCHAR(256)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Verified primary communication and account email address',
      sampleValues: ['e.sterling@enterprise.com', 'd.chen@apexglobal.io', 's.montgomery@venture.org'],
      distinctCount: 4210900,
      nullPercentage: 0,
    },
    {
      name: 'CUSTOMER_TIER',
      type: 'VARCHAR(32)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Calculated loyalty status: PLATINUM, GOLD, SILVER, STANDARD, ENTERPRISE',
      sampleValues: ['PLATINUM', 'GOLD', 'ENTERPRISE', 'STANDARD'],
      distinctCount: 5,
      nullPercentage: 0,
    },
    {
      name: 'LIFETIME_VALUE_USD',
      type: 'NUMBER(18,2)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Cumulative historic purchase value in USD',
      sampleValues: [4890.50, 1240.00, 18900.25, 340.00],
      distinctCount: 89400,
      nullPercentage: 0,
    },
    {
      name: 'COUNTRY_CODE',
      type: 'VARCHAR(2)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Two-letter ISO 3166-1 alpha-2 nationality code',
      sampleValues: ['US', 'CA', 'GB', 'DE', 'FR', 'JP'],
      distinctCount: 64,
      nullPercentage: 0,
    },
    {
      name: 'ACCOUNT_STATUS',
      type: 'VARCHAR(32)',
      nullable: false,
      isPrimaryKey: false,
      description: 'ACTIVE, SUSPENDED, DELETED, PENDING_VERIFICATION',
      sampleValues: ['ACTIVE', 'ACTIVE', 'ACTIVE', 'SUSPENDED'],
      distinctCount: 4,
      nullPercentage: 0,
    },
  ],
};

export const MOCK_TABLE_PRODUCT_DIM: CatalogTable = {
  id: 'tbl_product_dim',
  name: 'PRODUCT_DIM',
  database: 'RETAIL_ANALYTICS',
  schema: 'PRODUCTS',
  sourceId: 'src_sf_prod_sales',
  sourceName: 'Sales & Revenue Warehouse',
  description: 'Enterprise catalog item master, including SKU, category classifications, unit costs, supplier identifiers, and active merchandising flags.',
  owner: 'MERCHANDISING_ANALYTICS',
  rowCount: 184500,
  sizeBytes: 280000000,
  sizeFormatted: '267.0 MB',
  lastModifiedAt: '2026-08-16 14:00:00 UTC',
  lastSyncedAt: '3 mins ago',
  tags: ['production', 'master-data', 'products'],
  downstreamDashboards: ['Merchandising Margin', 'Inventory Velocity', 'Catalog Health'],
  ddl: `CREATE OR REPLACE TABLE RETAIL_ANALYTICS.PRODUCTS.PRODUCT_DIM (
    PRODUCT_ID NUMBER(38,0) NOT NULL,
    SKU VARCHAR(48) NOT NULL,
    PRODUCT_NAME VARCHAR(256) NOT NULL,
    CATEGORY_NAME VARCHAR(128) NOT NULL,
    SUBCATEGORY_NAME VARCHAR(128),
    UNIT_PRICE_USD NUMBER(12,2) NOT NULL,
    UNIT_COST_USD NUMBER(12,2) NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    SUPPLIER_ID VARCHAR(32),
    PRIMARY KEY (PRODUCT_ID)
);`,
  columns: [
    {
      name: 'PRODUCT_ID',
      type: 'NUMBER(38,0)',
      nullable: false,
      isPrimaryKey: true,
      description: 'Internal product identifier',
      sampleValues: [4001, 4002, 4003, 4004, 4005],
      distinctCount: 184500,
      nullPercentage: 0,
    },
    {
      name: 'SKU',
      type: 'VARCHAR(48)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Stock keeping unit barcode string',
      sampleValues: ['SKU-HW-SERVER-01', 'SKU-NET-SW-48P', 'SKU-STORAGE-NVME-2T'],
      distinctCount: 184500,
      nullPercentage: 0,
    },
    {
      name: 'PRODUCT_NAME',
      type: 'VARCHAR(256)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Full commercial item display title',
      sampleValues: ['Enterprise Rack Server R750', 'Managed 48-Port Switch PoE+', 'NVMe Gen4 2TB Enterprise Module'],
      distinctCount: 184500,
      nullPercentage: 0,
    },
    {
      name: 'CATEGORY_NAME',
      type: 'VARCHAR(128)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Top-tier merchandise department',
      sampleValues: ['Hardware Systems', 'Networking & Telecom', 'Storage Infrastructure'],
      distinctCount: 18,
      nullPercentage: 0,
    },
    {
      name: 'UNIT_PRICE_USD',
      type: 'NUMBER(12,2)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Standard manufacturer suggested retail price',
      sampleValues: [4890.00, 1850.00, 399.00, 120.00],
      distinctCount: 1420,
      nullPercentage: 0,
    },
    {
      name: 'UNIT_COST_USD',
      type: 'NUMBER(12,2)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Direct procurement landing cost per unit',
      sampleValues: [2900.00, 1100.00, 210.00, 65.00],
      distinctCount: 1380,
      nullPercentage: 0,
    },
  ],
};

export const MOCK_TABLE_CAMPAIGN_PERF: CatalogTable = {
  id: 'tbl_campaign_perf',
  name: 'CAMPAIGN_PERFORMANCE',
  database: 'MARKETING_ATTRIBUTION',
  schema: 'CAMPAIGNS',
  sourceId: 'src_sf_mktg_attr',
  sourceName: 'Marketing Attribution Mart',
  description: 'Aggregated multichannel marketing campaign metrics tracking daily spend, impressions, click-through rates, qualified pipeline conversions, and blended CAC.',
  owner: 'GROWTH_MARKETING',
  rowCount: 1290400,
  sizeBytes: 940000000,
  sizeFormatted: '896.0 MB',
  lastModifiedAt: '2026-08-17 18:00:00 UTC',
  lastSyncedAt: '1 hour ago',
  tags: ['marketing', 'attribution', 'roi', 'ad-networks'],
  downstreamDashboards: ['Marketing ROI & Blended CAC', 'Multi-Touch Attribution', 'Paid Channel Breakdown'],
  ddl: `CREATE OR REPLACE TABLE MARKETING_ATTRIBUTION.CAMPAIGNS.CAMPAIGN_PERFORMANCE (
    CAMPAIGN_ID VARCHAR(64) NOT NULL,
    DATE_KEY DATE NOT NULL,
    CHANNEL VARCHAR(32) NOT NULL,
    IMPRESSIONS NUMBER(38,0) NOT NULL,
    CLICKS NUMBER(38,0) NOT NULL,
    SPEND_USD NUMBER(18,2) NOT NULL,
    CONVERSIONS NUMBER(38,0) NOT NULL,
    PIPELINE_GENERATED_USD NUMBER(18,2),
    PRIMARY KEY (CAMPAIGN_ID, DATE_KEY)
);`,
  columns: [
    {
      name: 'CAMPAIGN_ID',
      type: 'VARCHAR(64)',
      nullable: false,
      isPrimaryKey: true,
      description: 'Unique advertising campaign code',
      sampleValues: ['CMP-2026-Q3-ENTERPRISE-SEARCH', 'CMP-2026-SUMMER-SOCIAL', 'CMP-2026-RETARGETING-DEV'],
      distinctCount: 840,
      nullPercentage: 0,
    },
    {
      name: 'DATE_KEY',
      type: 'DATE',
      nullable: false,
      isPrimaryKey: true,
      description: 'Reporting date partition',
      sampleValues: ['2026-08-17', '2026-08-16', '2026-08-15'],
      distinctCount: 730,
      nullPercentage: 0,
    },
    {
      name: 'CHANNEL',
      type: 'VARCHAR(32)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Channel source: GOOGLE_SEARCH, LINKEDIN_B2B, YOUTUBE_VIDEO, DISPLAY',
      sampleValues: ['GOOGLE_SEARCH', 'LINKEDIN_B2B', 'YOUTUBE_VIDEO'],
      distinctCount: 8,
      nullPercentage: 0,
    },
    {
      name: 'SPEND_USD',
      type: 'NUMBER(18,2)',
      nullable: false,
      isPrimaryKey: false,
      description: 'Daily media spend invested in channel currency converted to USD',
      sampleValues: [4890.00, 1250.40, 890.00, 15400.00],
      distinctCount: 12040,
      nullPercentage: 0,
    },
  ],
};

export const MOCK_CATALOG_HIERARCHY: CatalogDatabase[] = [
  {
    name: 'RETAIL_ANALYTICS',
    sourceId: 'src_sf_prod_sales',
    sourceName: 'Sales & Revenue Warehouse',
    schemaCount: 3,
    tableCount: 8,
    schemas: [
      {
        name: 'SALES',
        database: 'RETAIL_ANALYTICS',
        tableCount: 3,
        tables: [
          MOCK_TABLE_ORDER_FACT,
          {
            ...MOCK_TABLE_ORDER_FACT,
            id: 'tbl_sales_transactions',
            name: 'SALES_TRANSACTIONS',
            description: 'Individual payment authorization attempts and settle records.',
            rowCount: 210900400,
            sizeFormatted: '210.4 GB',
          },
          {
            ...MOCK_TABLE_ORDER_FACT,
            id: 'tbl_daily_revenue_agg',
            name: 'DAILY_REVENUE_AGG',
            description: 'Pre-aggregated daily rollup by territory, product line, and currency.',
            rowCount: 45200,
            sizeFormatted: '18.4 MB',
          },
        ],
      },
      {
        name: 'CUSTOMERS',
        database: 'RETAIL_ANALYTICS',
        tableCount: 3,
        tables: [
          MOCK_TABLE_CUSTOMER_DIM,
          {
            ...MOCK_TABLE_CUSTOMER_DIM,
            id: 'tbl_customer_loyalty_tier',
            name: 'CUSTOMER_LOYALTY_TIER',
            description: 'VIP points accrual, tier threshold criteria, and redemption history.',
            rowCount: 980000,
            sizeFormatted: '1.2 GB',
          },
          {
            ...MOCK_TABLE_CUSTOMER_DIM,
            id: 'tbl_customer_segments',
            name: 'CUSTOMER_SEGMENTS',
            description: 'ML propensity scores, churn risk percentiles, and dynamic audience tags.',
            rowCount: 4210900,
            sizeFormatted: '3.1 GB',
          },
        ],
      },
      {
        name: 'PRODUCTS',
        database: 'RETAIL_ANALYTICS',
        tableCount: 2,
        tables: [
          MOCK_TABLE_PRODUCT_DIM,
          {
            ...MOCK_TABLE_PRODUCT_DIM,
            id: 'tbl_inventory_snapshot',
            name: 'INVENTORY_SNAPSHOT',
            description: 'Daily warehouse inventory on-hand, safety stock thresholds, and stockouts.',
            rowCount: 890000,
            sizeFormatted: '780.0 MB',
          },
        ],
      },
    ],
  },
  {
    name: 'CUSTOMER_DATA_HUB',
    sourceId: 'src_sf_cust_hub',
    sourceName: 'Customer 360 Warehouse',
    schemaCount: 2,
    tableCount: 5,
    schemas: [
      {
        name: 'CORE',
        database: 'CUSTOMER_DATA_HUB',
        tableCount: 2,
        tables: [
          {
            ...MOCK_TABLE_CUSTOMER_DIM,
            id: 'tbl_account_profile',
            name: 'ACCOUNT_PROFILE',
            database: 'CUSTOMER_DATA_HUB',
            schema: 'CORE',
            description: 'Master enterprise business account entity and contract terms.',
          },
          {
            ...MOCK_TABLE_CUSTOMER_DIM,
            id: 'tbl_billing_addresses',
            name: 'BILLING_ADDRESSES',
            database: 'CUSTOMER_DATA_HUB',
            schema: 'CORE',
            description: 'Standardized verified corporate postal addresses for invoicing.',
          },
        ],
      },
      {
        name: 'EVENT_STREAMS',
        database: 'CUSTOMER_DATA_HUB',
        tableCount: 3,
        tables: [
          {
            ...MOCK_TABLE_ORDER_FACT,
            id: 'tbl_web_clickstream',
            name: 'WEB_CLICKSTREAM_EVENTS',
            database: 'CUSTOMER_DATA_HUB',
            schema: 'EVENT_STREAMS',
            description: 'Raw high-throughput frontend interaction events collected via Snowplow.',
            rowCount: 890000000,
            sizeFormatted: '820.0 GB',
          },
          {
            ...MOCK_TABLE_ORDER_FACT,
            id: 'tbl_session_engagement',
            name: 'SESSION_ENGAGEMENT',
            database: 'CUSTOMER_DATA_HUB',
            schema: 'EVENT_STREAMS',
            description: 'Sessionization rollups tracking duration, bounce rate, and conversion paths.',
            rowCount: 45000000,
            sizeFormatted: '48.0 GB',
          },
        ],
      },
    ],
  },
  {
    name: 'MARKETING_ATTRIBUTION',
    sourceId: 'src_sf_mktg_attr',
    sourceName: 'Marketing Attribution Mart',
    schemaCount: 1,
    tableCount: 2,
    schemas: [
      {
        name: 'CAMPAIGNS',
        database: 'MARKETING_ATTRIBUTION',
        tableCount: 2,
        tables: [
          MOCK_TABLE_CAMPAIGN_PERF,
          {
            ...MOCK_TABLE_CAMPAIGN_PERF,
            id: 'tbl_ad_spend_channel',
            name: 'AD_SPEND_CHANNEL',
            description: 'Raw invoice reconciliation feeds from Google Ads, Meta, and LinkedIn.',
          },
        ],
      },
    ],
  },
];

export const MOCK_SAMPLE_DATA_ORDER_FACT = [
  {
    ORDER_ID: 90841201,
    ORDER_NUMBER: 'ORD-2026-88912',
    CUSTOMER_ID: 1004921,
    ORDER_TIMESTAMP: '2026-08-17 21:14:02',
    ORDER_STATUS: 'COMPLETED',
    NET_AMOUNT: 149.99,
    TAX_AMOUNT: 12.37,
    SHIPPING_AMOUNT: 0.00,
    TOTAL_AMOUNT: 162.36,
    PAYMENT_METHOD: 'STRIPE_CARD',
    CURRENCY_CODE: 'USD',
    IS_EXPEDITED_SHIPPING: false,
    FULFILLMENT_CENTER_ID: 'WH-EAST-04',
    CREATED_AT: '2026-08-17 21:14:15',
  },
  {
    ORDER_ID: 90841202,
    ORDER_NUMBER: 'ORD-2026-88913',
    CUSTOMER_ID: 1083920,
    ORDER_TIMESTAMP: '2026-08-17 21:15:33',
    ORDER_STATUS: 'PROCESSING',
    NET_AMOUNT: 42.50,
    TAX_AMOUNT: 3.51,
    SHIPPING_AMOUNT: 9.99,
    TOTAL_AMOUNT: 56.00,
    PAYMENT_METHOD: 'APPLE_PAY',
    CURRENCY_CODE: 'USD',
    IS_EXPEDITED_SHIPPING: true,
    FULFILLMENT_CENTER_ID: 'WH-CENTRAL-01',
    CREATED_AT: '2026-08-17 21:15:45',
  },
  {
    ORDER_ID: 90841203,
    ORDER_NUMBER: 'ORD-2026-88914',
    CUSTOMER_ID: 2093181,
    ORDER_TIMESTAMP: '2026-08-17 21:16:01',
    ORDER_STATUS: 'COMPLETED',
    NET_AMOUNT: 1289.00,
    TAX_AMOUNT: 106.34,
    SHIPPING_AMOUNT: 14.99,
    TOTAL_AMOUNT: 1410.33,
    PAYMENT_METHOD: 'STRIPE_CARD',
    CURRENCY_CODE: 'USD',
    IS_EXPEDITED_SHIPPING: false,
    FULFILLMENT_CENTER_ID: 'WH-WEST-02',
    CREATED_AT: '2026-08-17 21:16:12',
  },
  {
    ORDER_ID: 90841204,
    ORDER_NUMBER: 'ORD-2026-88915',
    CUSTOMER_ID: 1004921,
    ORDER_TIMESTAMP: '2026-08-17 21:17:40',
    ORDER_STATUS: 'REFUNDED',
    NET_AMOUNT: 320.40,
    TAX_AMOUNT: 26.43,
    SHIPPING_AMOUNT: 0.00,
    TOTAL_AMOUNT: 346.83,
    PAYMENT_METHOD: 'PAYPAL',
    CURRENCY_CODE: 'USD',
    IS_EXPEDITED_SHIPPING: false,
    FULFILLMENT_CENTER_ID: 'WH-EAST-04',
    CREATED_AT: '2026-08-17 21:18:02',
  },
  {
    ORDER_ID: 90841205,
    ORDER_NUMBER: 'ORD-2026-88916',
    CUSTOMER_ID: 3948201,
    ORDER_TIMESTAMP: '2026-08-17 21:19:11',
    ORDER_STATUS: 'COMPLETED',
    NET_AMOUNT: 89.00,
    TAX_AMOUNT: 7.34,
    SHIPPING_AMOUNT: 4.99,
    TOTAL_AMOUNT: 101.33,
    PAYMENT_METHOD: 'STRIPE_CARD',
    CURRENCY_CODE: 'USD',
    IS_EXPEDITED_SHIPPING: true,
    FULFILLMENT_CENTER_ID: 'WH-EAST-04',
    CREATED_AT: '2026-08-17 21:19:30',
  },
  {
    ORDER_ID: 90841206,
    ORDER_NUMBER: 'ORD-2026-88917',
    CUSTOMER_ID: 4019283,
    ORDER_TIMESTAMP: '2026-08-17 21:20:44',
    ORDER_STATUS: 'COMPLETED',
    NET_AMOUNT: 2450.00,
    TAX_AMOUNT: 202.12,
    SHIPPING_AMOUNT: 0.00,
    TOTAL_AMOUNT: 2652.12,
    PAYMENT_METHOD: 'INVOICE_NET30',
    CURRENCY_CODE: 'USD',
    IS_EXPEDITED_SHIPPING: true,
    FULFILLMENT_CENTER_ID: 'WH-CENTRAL-01',
    CREATED_AT: '2026-08-17 21:21:05',
  },
  {
    ORDER_ID: 90841207,
    ORDER_NUMBER: 'ORD-2026-88918',
    CUSTOMER_ID: 1083920,
    ORDER_TIMESTAMP: '2026-08-17 21:22:15',
    ORDER_STATUS: 'COMPLETED',
    NET_AMOUNT: 512.00,
    TAX_AMOUNT: 42.24,
    SHIPPING_AMOUNT: 9.99,
    TOTAL_AMOUNT: 564.23,
    PAYMENT_METHOD: 'STRIPE_CARD',
    CURRENCY_CODE: 'USD',
    IS_EXPEDITED_SHIPPING: false,
    FULFILLMENT_CENTER_ID: 'WH-WEST-02',
    CREATED_AT: '2026-08-17 21:22:38',
  },
];

export const MOCK_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act_001',
    timestamp: '2 mins ago',
    user: {
      name: 'Marcus Vance',
      email: 'm.vance@acmecorp.internal',
      role: 'Data Architect',
    },
    action: 'Metadata catalog synchronized',
    resource: 'RETAIL_ANALYTICS.SALES',
    targetType: 'schema',
    status: 'success',
    details: 'Introspected 48 tables and 624 columns from Snowflake Native warehouse COMPUTE_WH_XL.',
    ipAddress: '10.240.12.88',
  },
  {
    id: 'act_002',
    timestamp: '8 mins ago',
    user: {
      name: 'System Scheduler (Redis Cache)',
      email: 'cache-worker@pi-analytics.internal',
      role: 'System Worker',
    },
    action: 'Schema discovery refreshed',
    resource: 'CUSTOMER_DATA_HUB.CORE',
    targetType: 'connection',
    status: 'success',
    details: 'Detected 2 updated column descriptions and refreshed PostgreSQL metadata index.',
    ipAddress: '127.0.0.1',
  },
  {
    id: 'act_003',
    timestamp: '24 mins ago',
    user: {
      name: 'Elena Rostova',
      email: 'e.rostova@acmecorp.internal',
      role: 'Data Analyst',
    },
    action: 'Exploration query executed',
    resource: 'RETAIL_ANALYTICS.SALES.ORDER_FACT',
    targetType: 'query',
    status: 'info',
    details: 'Executed aggregated revenue partition scan. Returned 100 rows in 142ms via Snowflake cache.',
    ipAddress: '10.240.15.102',
  },
  {
    id: 'act_004',
    timestamp: '1 hour ago',
    user: {
      name: 'System Scheduler',
      email: 'sync-worker@pi-analytics.internal',
      role: 'System Worker',
    },
    action: 'Warehouse introspection warning',
    resource: 'MARKETING_ATTRIBUTION.CAMPAIGNS',
    targetType: 'connection',
    status: 'warning',
    details: 'Warehouse auto-resume latency exceeded 12,000ms. Retried metadata fetch successfully.',
    ipAddress: '127.0.0.1',
  },
  {
    id: 'act_005',
    timestamp: '3 hours ago',
    user: {
      name: 'Marcus Vance',
      email: 'm.vance@acmecorp.internal',
      role: 'Data Architect',
    },
    action: 'New connection registered',
    resource: 'Sales & Revenue Warehouse (Snowflake)',
    targetType: 'connection',
    status: 'success',
    details: 'Configured Snowflake Native connector with role DATA_DISCOVERY_ROLE and warehouse COMPUTE_WH_XL.',
    ipAddress: '10.240.12.88',
  },
  {
    id: 'act_006',
    timestamp: '5 hours ago',
    user: {
      name: 'Marcus Vance',
      email: 'm.vance@acmecorp.internal',
      role: 'Data Architect',
    },
    action: 'User authentication successful',
    resource: 'SSO Okta Session',
    targetType: 'auth',
    status: 'success',
    details: 'Authenticated via SAML 2.0 Enterprise Identity Provider.',
    ipAddress: '10.240.12.88',
  },
];
